route: klvae_sit
model:
  model_arch: klvae_sit
  model_config:
    cfg_scale: 1.0
    thermal_normalizer: 1.0
    rgb_normalizer: 0.18215
    vae: ema
    eval_lpips: true
    thermal_vae_ckpt: ""
    thermal_vae_local_files_only: false
    rgb_vae_path: ""
    rgb_vae_repo: stabilityai/sd-vae-ft-ema
    rgb_vae_default_local_path: /root/autodl-fs/sd-vae-ft-ema
    rgb_vae_local_files_only: false
    thermal_vae_config:
      in_channels: 1
      out_channels: 1
      down_block_types: [DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D]
      up_block_types: [UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D]
      block_out_channels: [128, 256, 512, 512]
      layers_per_block: 2
      act_fn: silu
      latent_channels: 4
      norm_num_groups: 32
      sample_size: 256
      force_upcast: true
      use_quant_conv: true
      use_post_quant_conv: true
      mid_block_add_attention: true
    rgb_vae_config:
      in_channels: 3
      out_channels: 3
      down_block_types: [DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D, DownEncoderBlock2D]
      up_block_types: [UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D, UpDecoderBlock2D]
      block_out_channels: [128, 256, 512, 512]
      layers_per_block: 2
      act_fn: silu
      latent_channels: 4
      norm_num_groups: 32
      sample_size: 256
      force_upcast: true
      use_quant_conv: true
      use_post_quant_conv: true
      mid_block_add_attention: true
    sit_config:
      arch: L
      patch_size: 2
      num_classes: 1000
      injection_args:
        injection_method: concat
        replace_RGB: false
    transport_config:
      path_type: Linear
      prediction: velocity
      loss_weight:
    sample_ode:
      sampling_method: dopri5
      num_steps: 50
      atol: 1.0e-6
      rtol: 1.0e-3

datasets:
  datasets_folder: ./datasets_preprocess
  dataset_config_root: psl_flow/configs/paper/datasets
  train_datasets: [DroneVehicle_night]
  val_datasets: [DroneVehicle_night]
  test_datasets: [DroneVehicle_night]
  target_val_dataset: DroneVehicle_night

training:
  num_epochs: 1000
  max_steps: -1
  num_samples_per_epoch: 10000
  train_batch_size: 16
  test_batch_size: 16
  num_workers: 8
  train_image_size: [256, 256]
  image_norm: normal
  optimizer:
    name: AdamW
    lr: 1.0e-4
    weight_decay: 0.0
  loss:
    name: paper_klvae_sit
    config:
  mixed_precision: false
  gradient_accumulation: 1
  check_val_every_n_epoch: 50
  limit_val_batches:
  checkpoint_save_top_k: 1
  disable_logger: false
  log_every_n_steps: 50

