name: psl-flow
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.7
  - pip:
      - -r requirements.txt
