# PyTorch Training Parameters
model:
  model_arch: psl_vae
  model_config:
    in_channels: 6
    out_channels: 6
    down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
    up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
    block_out_channels: [128, 256, 512, 512]
    layers_per_block: 2
    act_fn: silu
    latent_channels: 8
    norm_num_groups: 32
    sample_size: 256
    force_upcast: True
    use_quant_conv: True
    use_post_quant_conv: True
    mid_block_add_attention: True
    divisible: 8
    a_low_range: [0.8, 1.2]
    temperature_log_scale: 4.0
    env_log_scale: 4.0
    delta_clip: 0.25
    residual_blur_kernel: 9
    residual_blur_sigma: 2.0
    residual_gate_power: 1.0
    residual_use_highpass: True
    sample_posterior: True

datasets:
  datasets_folder: "./datasets_preprocess"
  train_datasets:
    - AVIID
    - FLIR
    - KAIST
  val_datasets:
    - AVIID
    - FLIR
    - KAIST
  test_datasets:
    - AVIID
    - FLIR
    - KAIST
  target_val_dataset: FLIR

training:
  num_epochs: 300
  num_samples_per_epoch: 10000
  train_batch_size: 16
  test_batch_size: 16
  num_workers: 8
  val_freq: 10
  train_image_size: [256, 256]
  optimizer:
    name: AdamW
    lr: 6e-5
    weight_decay: 1e-3
    momentum: 0.9
  scheduler:
    name: none
    args:
  loss:
    name: 'psl_vae'
    config:
      teacher:
        ckpt: checkpoints/physics/terb_net/teacher_best.pth
        strict_load: false
        vnums: 4
        erme_kernel: 5
        lambda_env_init: 0.1
        a_low_range: [0.8, 1.2]
        smp_model: Unet
        smp_encoder: resnet18
        smp_encoder_weights: null
      w_e: 0.25
      w_t: 1.0
      w_r: 0.25
      w_a: 0.1
      w_b: 0.25
      lambda_factor: 1.0
      lambda_phys: 1.0
      lambda_delta: 1.0
      lambda_img: 2.0
      lambda_edge: 0.25
      lambda_lpips: 0.25
      kl_weight: 1.0e-6
  mixed_precision: False
  training_stage: full
  checkpoint_monitor: val_all/FID
  checkpoint_mode: min
  checkpoint_save_top_k: 1
  checkpoint_save_last: True
