# PyTorch Training Parameters
model:
  model_arch: sit
  model_config:
    vae: ema
    arch: L
    patch_size: 2
    cfg_scale: 1.0
    cache_rate: 1
    thermal_normalizer: 1.0
    RGB_normalizer: 0.18215
    divisible: 16
    vae_model: psl_vae
    rgb_vae_model: klvae
    rgb_vae_latent_channels: 4
    injection_args:
      injection_method: concat
      replace_RGB: False
    vae_path: checkpoints/psl_vae/checkpoints/last.ckpt
    teacher:
      ckpt: checkpoints/physics/terb_net/teacher_best.pth
      strict_load: false
      vnums: 4
      erme_kernel: 5
      lambda_env_init: 0.1
      a_low_range: [0.8, 1.2]
      smp_model: Unet
      smp_encoder: resnet18
      smp_encoder_weights: null
    vae_config:
      in_channels: 6
      out_channels: 6
      down_block_types: ['DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D', 'DownEncoderBlock2D']
      up_block_types: ['UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D', 'UpDecoderBlock2D']
      block_out_channels: [128, 256, 512, 512]
      layers_per_block: 2
      act_fn: silu
      latent_channels: 8
      norm_num_groups: 32
      sample_size: 256
      force_upcast: True
      use_quant_conv: True
      use_post_quant_conv: True
      mid_block_add_attention: True
      divisible: 8
      a_low_range: [0.8, 1.2]
      temperature_log_scale: 4.0
      env_log_scale: 4.0
      delta_clip: 0.25
      residual_blur_kernel: 9
      residual_blur_sigma: 2.0
      residual_gate_power: 1.0
      residual_use_highpass: True
    transport_config:
      path_type: Linear
      prediction: velocity
      loss_weight: None

datasets:
  datasets_folder: "./datasets_preprocess"
  train_datasets:
    - AVIID
    - FLIR
    - KAIST
  val_datasets:
    - AVIID
    - FLIR
    - KAIST
  test_datasets:
    - AVIID
    - FLIR
    - KAIST
  target_val_dataset: FLIR

training:
  num_epochs: 300
  num_samples_per_epoch: 50000
  train_batch_size: 64
  test_batch_size: 16
  num_workers: 8
  val_freq: 50
  train_image_size: [256, 256]
  optimizer:
    name: AdamW
    lr: 1e-4
    weight_decay: 0.0
    momentum: 0.9
  scheduler:
    name: none
    args:
  loss:
    name: 'sit'
    config: None
  mixed_precision: False
  gradient_accumulation: 1
