dataset_index: 23

train:
  - datafolder_name: IR500K
    thermal_only: true
    thermal_key: thermal.png

val:
  - datafolder_name: IR500K
    thermal_only: true
    thermal_key: thermal.png

test:
  - datafolder_name: IR500K
    thermal_only: true
    thermal_key: thermal.png
